log:
    pattern:  /
    defaults: { _controller: "CoregenAdminBundle:Log:index" }

log_show:
    pattern:  /{id}/show
    defaults: { _controller: "CoregenAdminBundle:Log:show" }

log_new:
    pattern:  /new
    defaults: { _controller: "CoregenAdminBundle:Log:new" }

log_create:
    pattern:  /create
    defaults: { _controller: "CoregenAdminBundle:Log:create" }
    requirements: { _method: post }

log_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CoregenAdminBundle:Log:edit" }

log_update:
    pattern:  /{id}/update
    defaults: { _controller: "CoregenAdminBundle:Log:update" }
    requirements: { _method: post }

log_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CoregenAdminBundle:Log:delete" }
    requirements: { _method: post }

log_batch_actions:
    pattern:  /batchActions
    defaults: { _controller: "CoregenAdminBundle:Log:batchActions" }
    requirements: { _method: post }

